Vagrant.configure("2") do |config|
  config.vm.synced_folder ".", "/vagrant", disabled: true
  
  config.vm.define "yamzilS" do |control|
    control.vm.box = "ubuntu/jammy64"
    control.vm.hostname = "yamzilS"
    control.vm.network "private_network", ip: "192.168.56.110"
    control.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 1
    end

    # Step 1: Install K3s
    control.vm.provision "shell", inline: <<-SHELL
      sudo rm -f /etc/ssh/sshd_config.d/60-cloudimg-settings.conf
      echo "PasswordAuthentication yes" | sudo tee /etc/ssh/sshd_config.d/override.conf
      sudo systemctl reload ssh
      sudo apt-get update -y
      sudo apt-get install -y curl
      curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--node-ip=192.168.56.110 --flannel-iface=enp0s8 --write-kubeconfig-mode 644" sh -
      mkdir -p /home/vagrant/.kube
          # Wait for k3s.yaml to be created
      while ! sudo test -f /etc/rancher/k3s/k3s.yaml; do
        echo "Waiting for k3s.yaml..."
        sleep 5
      done
      sudo cp /etc/rancher/k3s/k3s.yaml /home/vagrant/.kube/config
      sudo chown vagrant:vagrant /home/vagrant/.kube/config
    SHELL

    # Step 2: Copy confs into VM
    control.vm.provision "file",
      source: "./confs",
      destination: "/home/vagrant/confs"

    # Step 3: Apply manifests
    control.vm.provision "shell", inline: <<-SHELL
      kubectl apply -f /home/vagrant/confs/
    SHELL
  end
end