Vagrant.configure("2") do |config|
  config.vm.synced_folder ".", "/vagrant", disabled: true
  
  config.vm.define "yamzilS" do |control|
    control.vm.box = "ubuntu/jammy64"
    control.vm.hostname = "yamzilS"
    control.vm.network "private_network", ip: "192.168.56.110"
    control.vm.provider "virtualbox" do |vb|
      vb.memory = 4096
      vb.cpus = 2
    end 
    control.vm.provision "file",
      source: "./confs",
      destination: "/home/vagrant/confs"
    control.vm.provision "shell", path: "scripts/install.sh"
  end
end